### ISSUE TITLE
[1.19.2]Can't merge two datapacks together

### ISSUE THREAD

**Issue by Tigrex-Dai** [KendallP4299/Complement-Creator-for-Technical-Enchant-Renewed-#1]
I've created two datapacks but when I put them together it doesn't work(They work well when exist alone in datapack folder). The first time when I opened the creator and built, it built together with the items I added before but the second it worked separatedly and I have no idea why this happens.
Now I've unpacked two packs and merged them manually (also change some .json files like ui.json and some bowcross etc.) but after I pack them together, it doesn't work as well. Is that because of the format of the .zip?
I'm confused and looking forward to your help, thx.
[kamura2.zip](https://github.com/KendallP4299/Complement-Creator-for-Technical-Enchant-Renewed-/files/10378082/kamura2.zip)
[kamurapack.zip](https://github.com/KendallP4299/Complement-Creator-for-Technical-Enchant-Renewed-/files/10378083/kamurapack.zip)
[combine.zip](https://github.com/KendallP4299/Complement-Creator-for-Technical-Enchant-Renewed-/files/10378084/combine.zip)

**Comment by Frektip** [comment]
I think it is because Complement Creator use the same function path ("complement"), so when you use both of them at the same time they get overwritten. I would recommend to add all the item ID's that you need in a single build (at least for now)

**Comment by KendallP4299** [comment]
I went ahead and updated the code to allow you to enter a custom namespace every time you build a complement. Be careful not to reuse path names.

**Comment by Tigrex-Dai** [comment]
Thanks a lot! I've figured out a temperorary solution several days ago, just follow the format of preset (gobber2) to add my mod items and then rename the folder as gobber2, it's a bit silly but it works hahah

**Comment by KendallP4299** [comment]
glad you were able to get it to work, hopefully you wont have to worry about that again!
